###############################################################################
# Dock
###############################################################################
#
# Interface to a mock ROS1 style move base action server.
#
###############################################################################

####################
# Goal
####################

geometry_msgs/PoseStamped target_pose

---
####################
# Result
####################

string message

---

####################
# Feedback
####################

geometry_msgs/PoseStamped base_position
