%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/rolling/.*$
%global __requires_exclude_from ^/opt/ros/rolling/.*$

Name:           ros-rolling-py-trees-ros-interfaces
Version:        2.0.3
Release:        4%{?dist}%{?release_suffix}
Summary:        ROS py_trees_ros_interfaces package

License:        BSD
URL:            http://ros.org/wiki/py_trees_ros_interfaces
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-rolling-action-msgs
Requires:       ros-rolling-diagnostic-msgs
Requires:       ros-rolling-geometry-msgs
Requires:       ros-rolling-rosidl-default-runtime
Requires:       ros-rolling-unique-identifier-msgs
Requires:       ros-rolling-ros-workspace
BuildRequires:  ros-rolling-action-msgs
BuildRequires:  ros-rolling-ament-cmake
BuildRequires:  ros-rolling-diagnostic-msgs
BuildRequires:  ros-rolling-geometry-msgs
BuildRequires:  ros-rolling-rosidl-default-generators
BuildRequires:  ros-rolling-unique-identifier-msgs
BuildRequires:  ros-rolling-ros-workspace
BuildRequires:  ros-rolling-rosidl-typesupport-fastrtps-c
BuildRequires:  ros-rolling-rosidl-typesupport-fastrtps-cpp
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}
Provides:       ros-rolling-rosidl-interface-packages(member)

%if 0%{?with_tests}
BuildRequires:  ros-rolling-ament-lint-common
%endif

%if 0%{?with_weak_deps}
Supplements:    ros-rolling-rosidl-interface-packages(all)
%endif

%description
Interfaces used by py_trees_ros and py_trees_ros_tutorials.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/rolling" \
    -DAMENT_PREFIX_PATH="/opt/ros/rolling" \
    -DCMAKE_PREFIX_PATH="/opt/ros/rolling" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/rolling

%changelog
* Sat Jan 28 2023 Daniel Stonier <d.stonier@gmail.com> - 2.0.3-4
- Autogenerated by Bloom

* Sun Jan 22 2023 Daniel Stonier <d.stonier@gmail.com> - 2.0.3-3
- Autogenerated by Bloom

* Sun Jan 22 2023 Daniel Stonier <d.stonier@gmail.com> - 2.0.3-2
- Autogenerated by Bloom

* Sun May 22 2022 Daniel Stonier <d.stonier@gmail.com> - 2.0.3-1
- Autogenerated by Bloom

