##############################################################################
#
# Close an existing snapshot stream.
#
# Request
#   topic_name: snapshot stream to close
#
# Response
#   result: success/failure of the operation (failure: stream did not exist)
#
##############################################################################

string topic_name

---

bool result
